version: '3.9'
services:
  db:
    image: postgres:15
    container_name: nextjs_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextjs_network

volumes:
  postgres_data:

networks:
  nextjs_network:
